### PR TITLE
Migrate Grafana

### PR DESCRIPTION
**Pull request by jac**
New Grafana 7 set up and configured via provisioning at https://new.grafana.netsoc.dev (user + pass in secrets) 
"new" subdomain until ready to deprecate current setup 

This is the list of Dashboards on the current setup

Current Dashboards List

Prom Metrics on new setup:
- cadvisor
- minecraft server
- node exporter
- proxmox
- traefik
- site-up
- prom itself
- exporter exporter itself

We will have to go through all the dashboards on the current setup and migrate whatever we want to keep to jsonnet/grafonnet.
As well as create dashboards for new metrics.
The new setup currently has one, pretty minimal, example dashboard set up

### CODE REVIEW

**Comment by ericm** [comment]
we can add pterodactyl active eggs / ram etc

**Comment by ocanty** [comment]
> we can add pterodactyl active eggs / ram etc

are there are any exporters? or just monitor the processes with node-exporter

**Comment by ericm** [comment]
> > we can add pterodactyl active eggs / ram etc
> 
> are there are any exporters? or just monitor the processes with node-exporter

https://github.com/pterodactyl/panel/issues/1543 dont think so

**Comment by ericm** [comment]
Would it be possible to get statistics on network usage for each host, vm and vlan?

**Comment by ocanty** [comment]
each host, each vm can be done with proxmox-exporter

each vlan might have to be done with node-exporter installed on vyos

**Comment by ericm** [comment]
Nice! Would be quite useful to see down the line if our internal network gets congested when we have everything running on the new setup

**Comment by ocanty** [comment]
Number of 500s, HDD space
Bot stats, CPU usage, RAM usage, 
Stats exported by netsocadmin
VM up status
Blackbox exporter probes

Temps

**Pull request merged**
